name: "Comicbot test"

on:
  workflow_dispatch:
    branches: [ develop ]
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    - name: Build
      run: go build -v ./comicbot.go

    - name: Run
      run: go run comicbot.go
