name: "Comicbot test"

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: '7338dba4484869cc029f4f03ca61b9982a770028' # Checkout previous version supporting Dunce
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - name: Run
      run: go run comicbot.go
