name: "Comicbot prod"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Run
      run: go run comicbot.go
